baseURL = "/"
title = "泉州しゃこクラブHPへようこそ"
author = "泉州しゃこクラブ"
copyright = "Copyright © 2020-, Sensyu Syako Club; all rights reserved."
paginate = 10
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[Params]
site_name_jp = "泉州しゃこクラブ"
author = "泉州しゃこクラブ"
description = "泉州獣医臨床研究会"

[menu]

  
  [[menu.main]]
    identifier = "about"
    name = "研究会について"
    url = "/about/"
    weight = 2
  [[menu.main]]
    parent = "about"
    name = "活動内容"
    url = "/about/"
    weight = 1
  [[menu.main]]
    parent = "about"
    name = "会員病院"
    url = "/member/"
    weight = 2
  [[menu.main]]
    parent = "about"
    name = "運営組織"
    url = "/about/#運営組織"
    weight = 3
  [[menu.main]]
    identifier = "news"
    name = "お知らせ"
    url = "/news/"
    weight = 4
  [[menu.main]]
    identifier = "recruit"
    name = "求人情報"
    url = "/recruit/"
    weight = 9
  [[menu.main]]
    identifier = "link"
    name = "リンク"
    url = "/link/"
    weight = 10


[taxonomies]
category = "categories"
tag = "tags"
series = "series"
recruitment = "recruitment"


[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[services]

  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true

[markup.goldmark.renderer]
  unsafe = true