# GitHubのブランチ指定
backend:
  name: github
  #name: git-gateway
  repo: komaizukoshitsu/sensyuvets
  branch: master

local_backend: true

publish_mode: editorial_workflow
locale: 'ja'
media_folder: "static/images"
public_folder: "/images"

# 編集オブジェクト
collections:
  - name: "news" # 管理画面のパスで使う　例：/admin/collections/blog
    label: "お知らせ" # 管理画面のサイドバーで使う
    folder: "content/news" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    create: true # 新しいページを作ることを許可する
    slug: "{{year}}{{month}}{{day}}{{minute}}{{second}}" # Markdownのファイル名　例：YYYY-MM-DD-title.md
    editor:
      preview: true
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime", format: "YYYY,MM,DD"}
      # - {label: "更新日", name: "updateDate", widget: "datetime", format: "YYYY,MM,DD"}
      # - {label: "サムネイル画像", name: "thumbnail", widget: "image"}
      - {label: "本文", name: "body", widget: "markdown"}
  - name: "member"
    label: "会員病院"
    folder: "content/member"
    create: true
    slug: "{{year}}{{month}}{{day}}{{minute}}{{second}}"
    fields:
      - {label: "病院名", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime", format: "YYYY,MM,DD"}
      - {label: "病院説明", name: "description", widget: "string"}
      - {label: "募集の有無", name: "recruitment", widget: "select", options: ["獣医師募集中", "募集なし"]}
      - {label: "市町村名", name: "tags", widget: "select", options: ["和泉市", "泉大津市", "泉佐野市", "貝塚市", "岸和田市", "熊取町", "堺市", "泉南市", "高石市", "田尻町", "忠岡町", "岬町"]}
      - {label: "サムネイル画像", name: "thumbnail", widget: "image"}
      - {label: "本文", name: "body", widget: "markdown"}
  - name: "recruit"
    label: "採用情報"
    folder: "content/recruit"
    create: true
    slug: "{{year}}{{month}}{{day}}{{minute}}{{second}}"
    fields:
      - {label: "病院名", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime", format: "YYYY,MM,DD"}
      - {label: "募集人数", name: "description", widget: "string"}
      - {label: "市町村名", name: "tags", widget: "select", options: ["和泉市", "泉大津市", "泉佐野市", "貝塚市", "岸和田市", "熊取町", "堺市", "泉南市", "高石市", "田尻町", "忠岡町", "岬町"]}
      - {label: "サムネイル画像", name: "thumbnail", widget: "image"}
      - {label: "本文", name: "body", widget: "markdown"}