# GitHubのブランチ指定
backend:
  name: git-gateway
  # repo: komaizukoshitsu/sensyuvets.git
  # branch: master
  branch: master
publish_mode: editorial_workflow
locale: 'ja'
media_folder: "static/images"
public_folder: "/images"

# 編集オブジェクト
collections:
  - name: "news" # 管理画面のパスで使う　例：/admin/collections/blog
    label: "お知らせ" # 管理画面のサイドバーで使う
    folder: "content/news" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    create: true # 新しいページを作ることを許可する
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Markdownのファイル名　例：YYYY-MM-DD-title.md
    editor:
      preview: true
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "作成日", name: "createdateDate", widget: "datetime", format: "YYYY,MM,DD"}
      - {label: "更新日", name: "updateDate", widget: "datetime", format: "YYYY,MM,DD"}
      - {label: "サムネイル画像", name: "thumbnail", widget: "image"}
      - {label: "本文", name: "body", widget: "markdown"}
  - label: "Member" # 管理画面のサイドバーで使う
    name: "member" # 管理画面のパスで使う　例：/admin/collections/blog
    folder: "content/member" # Markdownを保存するディレクトリ。Hugoのsectionにあたる
    create: true # 新しいページを作ることを許可する
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Markdownのファイル名　例：YYYY-MM-DD-title.md
    fields: # ページ作成画面で使う。Front Matterの値を書く
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "サムネイル画像", name: "thumbnail", widget: "image"}
      - {label: "レーティング", name: "rating", widget: "number"}
      - {label: "本文", name: "body", widget: "markdown"}
  - name: "recruit"
    label: "採用情報"
    folder: "content/recruit"
    create: true
    slug: "{{id}}"
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "datetime"}
      - {label: "募集人数", name: "description", widget: "string"}
      - {label: "市町村名", name: "tag", widget: "string"}
      - {label: "サムネイル画像", name: "thumbnail", widget: "image"}
      - {label: "本文", name: "body", widget: "markdown"}