# GitHubのブランチ指定
backend:
  name: github
  #name: git-gateway
  repo: komaizukoshitsu/sensyuvets
  branch: master

local_backend: true

publish_mode: editorial_workflow
locale: 'ja'
timezone: Asia/Tokyo
media_folder: "static/images"
public_folder: "/images"

# 編集オブジェクト
collections:
  - name: "news"
    label: "お知らせ"
    folder: "content/news"
    create: true
    slug: "{{year}}{{month}}{{day}}{{minute}}{{second}}"
    editor:
      preview: true
    fields:
      - {label: "タイトル", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "date", format: "YYYY,MM,DD"}
      - {label: "本文", name: "body", widget: "markdown"}
  - name: "member"
    label: "会員病院"
    folder: "content/member"
    create: true
    slug: "{{year}}{{month}}{{day}}{{minute}}{{second}}"
    fields:
      - {label: "病院名", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "date", format: "YYYY,MM,DD"}
      - {label: "病院説明", name: "description", widget: "string"}
      - label: "市町村名"
        name: "city"
        widget: "select"
        options: [
          "和泉市", "泉大津市", "泉佐野市", "貝塚市", "岸和田市", "熊取町", "堺市", "泉南市", "高石市", "田尻町", "忠岡町", "岬町"
          ]
      - {label: "サムネイル画像", name: "thumbnail", widget: "image", required: false}
      - label: "病院について"
        name: "info"
        widget: "object"
        fields:
          - {label: "院長", name: "director", widget: "string"}
          - {label: "開院", name: "open", widget: "string"}
          - {label: "従業員", name: "staff", widget: "string"}
          - {label: "診療対象動物", name: "animals", widget: "string"}
          - {label: "特色", name: "features", widget: "string"}
          - {label: "WEBサイト", name: "website", widget: "string"}
      - label: "連絡先"
        name: "contact"
        widget: "object"
        fields:
          - {label: "住所", name: "address", widget: "string"}
          - {label: "TEL", name: "tel", widget: "string"}
          - {label: "FAX", name: "fax", widget: "string"}
          - {label: "MAIL", name: "mail", widget: "string"}
      - label: "獣医師募集"
        name: "recruit"
        widget: "object"
        fields:
          - {label: "募集する", name: "recruiting", widget: "boolean", default: false}
          - {label: "給与", name: "salary", widget: "string"}
          - {label: "休日", name: "holiday", widget: "string"}
          - {label: "賞与・昇給", name: "bonus", widget: "string"}
          - {label: "手当", name: "allowance", widget: "string"}
          - {label: "福利厚生", name: "welfare", widget: "string"}
          - {label: "その他", name: "option", widget: "string"}
  - name: "recruit"
    label: "採用情報"
    folder: "content/recruit"
    create: true
    slug: "{{year}}{{month}}{{day}}{{minute}}{{second}}"
    fields:
      - {label: "病院名", name: "title", widget: "string"}
      - {label: "公開日", name: "date", widget: "date", format: "YYYY,MM,DD"}
      - {label: "募集人数", name: "description", widget: "string"}
      - {label: "市町村名", name: "city", widget: "select", options: ["和泉市", "泉大津市", "泉佐野市", "貝塚市", "岸和田市", "熊取町", "堺市", "泉南市", "高石市", "田尻町", "忠岡町", "岬町"]}
      - {label: "サムネイル画像", name: "thumbnail", widget: "image", required: false}
      - {label: "本文", name: "body", widget: "markdown"}